#version 440

layout(location = 0) in vec2 qt_TexCoord0;
layout(location = 0) out vec4 fragColor;

layout(binding = 1) uniform sampler2D landMask;

layout(std140, binding = 0) uniform buf {
  mat4 qt_Matrix;
  float qt_Opacity;
  vec2 resolution;
  float time;        // seconds — drives rotation
  float globeRadius; // sphere radius in NDC
  vec3 baseColor;    // tile colour
};

#define PI 3.14159265359
#define TAU 6.28318530718
#define ROTATION_SPEED 0.1
#define HEX_SCALE 150.0 // num of rows of dots fit from pole to pole
#define GAP_WIDTH 0.1   // thin dark gap between tiles
#define TILE_FRACTION (1.0 - GAP_WIDTH)
#define LAND_THRESHOLD 0.5
#define VIEW_TILT -0.5 // radians. negative = look down at northern hemisphere
#define FOG_START 0.0  // dot product between surface normal and camera dir
#define FOG_END -0.6

// ─── Utility ───────────────────────────────────────────────────────────────

float raySphere(vec3 ro, vec3 rd, float r) {
  float b = dot(ro, rd);
  float c = dot(ro, ro) - r * r;
  float disc = b * b - c;
  if (disc < 0.0)
    return -1.0;
  return -b - sqrt(disc);
}

mat3 rotY(float a) {
  float c = cos(a), s = sin(a);
  return mat3(c, 0, s, 0, 1, 0, -s, 0, c);
}

// ─── Perfect 3D Staggered Tiling ───────────────────────────────────────────
// Finds the center generated by a specific latitude row `r`
void getTileCenter(float r, float numRows, float lon, out vec3 c, out vec2 geo,
                   out float id) {
  float centerLat = r * PI / numRows - PI * 0.5;
  // Number of columns in this row proportional to circumference
  float numCols = max(1.0, floor(2.0 * numRows * cos(centerLat) + 0.5));

  // Shift every second row by half a step to create staggered (hex-like)
  // packing
  float phase = 0.5 * mod(r, 2.0);
  float u = (lon + PI) / TAU * numCols - phase;
  float col = floor(u + 0.5);
  col = mod(col, numCols); // Wrap longitude

  float centerLon = (col + phase) / numCols * TAU - PI;

  geo = vec2(centerLat, centerLon);
  c = vec3(cos(centerLat) * cos(centerLon), sin(centerLat),
           cos(centerLat) * sin(centerLon));
  id = fract(sin(r * 123.456 + col * 789.123) * 43210.12);
}

// ─── Main ──────────────────────────────────────────────────────────────────

vec4 shadeSurface(float t, vec3 camPos, vec3 rd) {
  vec3 hitPos = camPos + rd * t;
  vec3 normal = normalize(hitPos / globeRadius);
  vec3 viewDir = normalize(camPos - hitPos);
  float ndotv = dot(normal, viewDir);

  // Spin the globe around Y
  vec3 rotNormal = rotY(time * ROTATION_SPEED) * normal;

  // Lat/lon mapping
  float lat = asin(clamp(rotNormal.y, -1.0, 1.0));
  float lon = atan(rotNormal.z, rotNormal.x);

  // ── Tile Evaluation ────────────────────────────────────────────────
  float numRows = HEX_SCALE;
  float v = (lat + PI * 0.5) / PI * numRows;

  // Find the two nearest latitude rows
  float r1 = clamp(floor(v), 0.0, numRows);
  float r2 = clamp(r1 + 1.0, 0.0, numRows);

  vec3 c1, c2;
  vec2 geo1, geo2;
  float id1, id2;
  getTileCenter(r1, numRows, lon, c1, geo1, id1);
  getTileCenter(r2, numRows, lon, c2, geo2, id2);

  // True 3D isotropic distance on the sphere surface
  float d1 = length(rotNormal - c1);
  float d2 = length(rotNormal - c2);

  vec2 bestGeo;
  float bestId;
  float minDist;

  if (d1 < d2) {
    minDist = d1;
    bestId = id1;
    bestGeo = geo1;
  } else {
    minDist = d2;
    bestId = id2;
    bestGeo = geo2;
  }

  // ── Land Mask ──────────────────────────────────────────────────────
  vec2 mapUV = vec2(0.5 - bestGeo.y / TAU, bestGeo.x / PI + 0.5);
  float land = texture(landMask, mapUV).r;
  if (land < LAND_THRESHOLD) {
    return vec4(0.0);
  }

  // ── Gap Rendering ──────────────────────────────────────────────────
  float maxRadius = (PI / numRows) * 0.5; // arc radius for touching tiles
  float tileRadius = maxRadius * TILE_FRACTION;

  if (minDist > tileRadius) {
    return vec4(0.0);
  }

  // Smooth antialiased tile edge
  float tileEdgeAlpha = smoothstep(tileRadius, tileRadius - 0.005, minDist);

  // ── Coloring ───────────────────────────────────────────────────────
  float brightness = 0.2 + 0.8 * bestId;
  vec3 tileColor = baseColor * brightness * 0.7;

  float edgeHighlight =
      smoothstep(tileRadius * 0.7, tileRadius * 0.95, minDist);
  tileColor = mix(tileColor, baseColor * brightness * 0.9, edgeHighlight * 0.4);

  // ── Depth fog & Fresnel ────────────────────────────────────────────
  float fog = smoothstep(FOG_END, FOG_START, ndotv);

  // Fresnel rim brightening: use abs(ndotv) so both front and back edges glow
  float fresnel = pow(clamp(1.0 - abs(ndotv), 0.0, 1.0), 2.5);
  tileColor += baseColor * fresnel * 0.1;

  vec3 col = tileColor * fog;
  float alpha = fog * qt_Opacity * tileEdgeAlpha;

  return vec4(col * alpha, alpha);
}

void main() {
  vec2 uv = qt_TexCoord0 * 2.0 - 1.0;
  float aspect = resolution.x / resolution.y;
  uv.x *= aspect;

  // Camera: fixed position, tilted slightly above
  float camDist = 3.5;
  vec3 camPos = vec3(0.0, camDist * sin(VIEW_TILT), camDist * cos(VIEW_TILT));
  vec3 forward = normalize(-camPos);
  vec3 worldUp = vec3(0, 1, 0);
  vec3 right = normalize(cross(forward, worldUp));
  vec3 up = cross(right, forward);
  vec3 rd = normalize(forward * 1.8 + right * uv.x + up * uv.y);

  // Intersect ray with globe
  float b = dot(camPos, rd);
  float c = dot(camPos, camPos) - globeRadius * globeRadius;
  float disc = b * b - c;

  if (disc < 0.0) {
    fragColor = vec4(0.0);
    return;
  }

  float t1 = -b - sqrt(disc); // Front hit
  float t2 = -b + sqrt(disc); // Back hit

  vec4 frontColor = vec4(0.0);
  if (t1 > 0.0)
    frontColor = shadeSurface(t1, camPos, rd);

  vec4 backColor = vec4(0.0);
  if (t2 > 0.0)
    backColor = shadeSurface(t2, camPos, rd);

  // Alpha composite: front over back
  fragColor = frontColor + backColor * (1.0 - frontColor.a);
}
